// frontend-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <div style="padding:20px">
      <h2>Students (Angular)</h2>
      <ul>
        <li *ngFor="let s of students">{{s.name}} ({{s.email}})</li>
      </ul>

      <h3>Register</h3>
      <form (ngSubmit)="create()">
        <div><input [(ngModel)]="model.name" name="name" placeholder="name" /></div>
        <div><input [(ngModel)]="model.email" name="email" placeholder="email" /></div>
        <div><input [(ngModel)]="model.dob" name="dob" placeholder="YYYY-MM-DD" /></div>
        <button type="submit">Create</button>
      </form>
    </div>
  `
})
export class AppComponent {
  students: any[] = [];
  model: any = {name:'', email:'', dob:''};

  constructor() { this.load(); }

  async load(){
    try{
      const res = await fetch('/api/students');
      this.students = await res.json();
    }catch(e){}
  }

  async create(){
    const res = await fetch('/api/students', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify(this.model)});
    const created = await res.json();
    this.students.push(created);
    this.model = {name:'',email:'',dob:''};
  }
}

// frontend-react/src/App.js
import React, { useEffect, useState } from 'react';

function App() {
  const [students, setStudents] = useState([]);
  const [form, setForm] = useState({name:'', email:'', dob:''});

  useEffect(()=>{
    fetch('/api/students')
      .then(r=>r.json())
      .then(setStudents)
      .catch(()=>{});
  },[]);

  const submit = async (e) => {
    e.preventDefault();
    const res = await fetch('/api/students', {
      method: 'POST', headers: {'Content-Type':'application/json'},
      body: JSON.stringify(form)
    });
    const created = await res.json();
    setStudents(s=>[...s, created]);
    setForm({name:'',email:'',dob:''});
  }

  return (
    <div style={{padding:20}}>
      <h2>Students (React)</h2>
      <ul>
        {students.map(s=> <li key={s.id}>{s.name} ({s.email})</li>)}
      </ul>

      <h3>Register</h3>
      <form onSubmit={submit}>
        <div><input placeholder="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} /></div>
        <div><input placeholder="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} /></div>
        <div><input placeholder="YYYY-MM-DD" value={form.dob} onChange={e=>setForm({...form,dob:e.target.value})} /></div>
        <button type="submit">Create</button>
      </form>
    </div>
  );
}

export default App;
